import { ChakraProvider, Container } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Navbar } from "../components/navbar";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider>
      <Head>
        <title>Minimal Retirement Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxW="container.lg" mb={4}>
        <Component {...pageProps} />
      </Container>
    </ChakraProvider>
  );
}
