import Head from "next/head";
import { Button } from "@chakra-ui/react";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Minimal Retirement Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello World
      <Button>Test</Button>
    </main>
  );
}
